### ISSUE TITLE
[TRANSACTION] Delivery Transaction

### ISSUE THREAD

**Issue by xpdavid** [DistributedTeam/Cassandra#4]

**Comment by langyanbin0314** [comment]
Q1: Find orders by `O_W_ID`, `O_D_ID` and `O_CARRIER_ID` order by `O_ID asce`
Q2: Find order-lines by `OL_W_ID`, `OL_D_ID` and `OL_O_ID`
Q3: Find customer by `O_W_ID` and `O_D_ID`

**Comment by xpdavid** [comment]
Single-partition (Slide 1) https://docs.google.com/presentation/d/15NRqFw90KXQOrOkuhfjy0-h7f3DrZpIXQ6tYCl1W6G8/edit#slide=id.p
