### ISSUE TITLE
[TRANSACTION] Order-Status Transaction

### ISSUE THREAD

**Issue by xpdavid** [DistributedTeam/Cassandra#5]

**Comment by langyanbin0314** [comment]
Q1: Find the customer by `C_W_ID`, `C_D_ID` and `C_ID`
Q2: Find the order by `O_W_ID`, `O_D_ID` and `O_C_ID`
Q3: Order those found in Q2 by `O_ENTRY_D desc` and choose first one
Q4: Find the order-line by `OL_W_ID`, `OL_D_ID`, `OL_O_ID` and `OL_I_ID`

**Comment by xpdavid** [comment]
Single-partition (Slide 1) https://docs.google.com/presentation/d/15NRqFw90KXQOrOkuhfjy0-h7f3DrZpIXQ6tYCl1W6G8/edit#slide=id.p
