### ISSUE TITLE
[TRANSACTION] Stock-Level Transaction

### ISSUE THREAD

**Issue by xpdavid** [DistributedTeam/Cassandra#6]

**Comment by leshweyeewin** [comment]
Q1. Look up District by `D_ID` and `W_ID` (to get N = D NEXT_O_ID)

Q2. Find Order lines by `OL_O_ID` ∈ [N-L, N), `OL_D_ID` and `OL_W_ID` (to get S = {`OL_I_ID`})  (note: S can have duplicates)

Q3. Find Stock by `S_I_ID` and `S_W_ID` (to get S_Quantity)

=> Count++ if S_Quantity < T

**Comment by xpdavid** [comment]
Single-partition (Slide 1) https://docs.google.com/presentation/d/15NRqFw90KXQOrOkuhfjy0-h7f3DrZpIXQ6tYCl1W6G8/edit#slide=id.p
