### ISSUE TITLE
[TRANSACTION] Popular-Item Transaction 

### ISSUE THREAD

**Issue by xpdavid** [DistributedTeam/Cassandra#7]

**Comment by leshweyeewin** [comment]
Q1. Look up District by `D_ID` and `W_ID` (to get N = D_NEXT_O_ID)

Q2. Find Orders by `O_ID` ∈ [N-L, N), `O_D_ID` and `O_W_ID` (to get S = {O_ID}, O_ENTRY_D and O_C_ID)

Q3. Look up Customer by `C_ID` `C_W_ID` `C_D_ID` (to get C_FIRST, C_MIDDLE, C_LAST)

Q4. Find Order lines by `OL_O_ID` ∈ [N-L, N), `OL_D_ID` and `OL_W_ID` (to get OL_O_ID, OL_I_ID, OL_QUANTITY, Ix = {Order line})

Q5. Look up Item by I_ID (to get I_NAME)

=> Px = Px U X if X.OL_QUANTITY >= Y.OL_QUANTITY for X.OL_O_ID = Y.OL_O_ID = x, X ∈ Ix, x ∈ S

=> for each t ∈ Px,
S' = {t.OL_O_ID | t.OL_O_ID ∈ S}
% = |S'| / |S| × 100

**Comment by xpdavid** [comment]
Single-partition (Slide 1) https://docs.google.com/presentation/d/15NRqFw90KXQOrOkuhfjy0-h7f3DrZpIXQ6tYCl1W6G8/edit#slide=id.p
