### ISSUE TITLE
[TRANSACTION] Top-Balance Transaction

### ISSUE THREAD

**Issue by xpdavid** [DistributedTeam/Cassandra#8]

**Comment by elijahsk** [comment]
Q1. Look up for all warehouses (to get Warehouse number W_ID).
Q2. Look up for all districts by D_W_ID = W_ID (to get District number D_ID)
Q3. Look up for customers by C_W_ID = W_ID and C_D_ID = D_ID orderby C_BALANCE desc (to get Customer name C_FIRST, C_MIDDLE, C_LAST, Outstand balance C_BALANCE)
